<?php

return [
    'adminEmail' => 'admin@example.com',
    'supportEmail' => 'support@example.com',
    'senderEmail' => 'noreply@example.com',
    'senderName' => 'Example.com mailer',
    'user.passwordResetTokenExpire' => 3600,
    'user.passwordMinLength' => 8,
    'app.timezone' => 'Asia/Jakarta',
    'app.uploadPath' => '@frontend/web/public/uploads',
    'app.uploadUrl' => '/public/uploads',
    'app.qrPath' => '@frontend/web/public/uploads/qr',
    'app.qrUrl' => '/public/uploads/qr',
    'telegram.apiBaseUrl' => 'https://api.telegram.org',
    'telegram.botToken' => '',
    'report.defaultStatus' => 'submitted',
    'report.queueStatus' => 'submitted',
    'report.secretaryStatus' => 'secretary_review',
    'report.finalizedStatus' => 'secretary_finalized',
    'report.approvedStatus' => 'team_approved',
    'report.followUpStatus' => 'coordinator_follow_up',
    'report.closedStatus' => 'closed',
    'bsVersion' => '5.x',
];
